spring:
  application:
    name: treeze
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/treeze
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 8181